export { default as image1 } from "../../../public/ambassadors/ambassador1.jpg"
export { default as image2 } from "../../../public/ambassadors/ambassador2.jpg"
export { default as pc1 } from "../../../public/ambassadors/pc1.jpg"
export { default as pc3 } from "../../../public/ambassadors/pc3.jpg"
export { default as pc4 } from "../../../public/ambassadors/pc4.jpg"
export { default as pc5 } from "../../../public/ambassadors/pc5.jpg"
export { default as pc6 } from "../../../public/ambassadors/pc6.jpg"
export { default as pc7 } from "../../../public/ambassadors/pc7.jpg"
export { default as pc8 } from "../../../public/ambassadors/pc8.jpg"
export { default as pc9 } from "../../../public/ambassadors/pc9.jpg"
export { default as pc10 } from "../../../public/ambassadors/pc10.jpg"
export { default as pc2 } from "../../../public/ambassadors/pc2.jpg"
export { default as pc11 } from "../../../public/ambassadors/pc11.jpg"
export { default as gohimg_1 } from "../../../public/ambassadors/gohimg_1.jpg"
export { default as gohimg_2 } from "../../../public/ambassadors/gohimg_2.jpg"
export { default as gohimg_3 } from "../../../public/ambassadors/gohimg_3.jpg"
export { default as gohimg_4 } from "../../../public/ambassadors/gohimg_4.jpg"
export { default as gohimg_5 } from "../../../public/ambassadors/gohimg_5.jpg"
export { default as gohimg_6} from "../../../public/ambassadors/gohimg_6.jpg"
export { default as gohimg_7 } from "../../../public/ambassadors/gohimg_7.jpg"
export { default as gohimg_8 } from "../../../public/ambassadors/gohimg_8.jpg"
export { default as gohimg_9 } from "../../../public/ambassadors/gohimg_9.jpg"
export { default as gohimg_10 } from "../../../public/ambassadors/gohimg_10.jpg"
export { default as gohimg_11} from "../../../public/ambassadors/gohimg_11.jpg"
export { default as gohimg_12 } from "../../../public/ambassadors/gohimg_12.jpg"
export { default as gohimg_13 } from "../../../public/ambassadors/gohimg_13.jpg"
export { default as gohimg_14 } from "../../../public/ambassadors/gohimg_14.jpg"
export { default as gohimg_15 } from "../../../public/ambassadors/gohimg_15.jpg"
export { default as gohimg_16 } from "../../../public/ambassadors/gohimg_16.png"
export { default as gohimg_17 } from "../../../public/ambassadors/gohimg_17.png"


export { default as pic1 } from "../../../public/pics/pic1.jpg"
export { default as pic2 } from "../../../public/pics/pic2.jpg"
export { default as pic3 } from "../../../public/pics/pic3.jpg"
export { default as pic4 } from "../../../public/pics/pic4.jpg"
export { default as pic5 } from "../../../public/pics/pic5.jpg"
export { default as pic6} from "../../../public/pics/pic6.jpg"
export { default as pic7 } from "../../../public/pics/pic7.jpg"
export { default as pic9 } from "../../../public/pics/pic9.jpg"
export { default as pic10 } from "../../../public/pics/pic10.jpg"
export { default as pic11 } from "../../../public/pics/pic11.jpg"
export { default as pic12 } from "../../../public/pics/pic12.jpg"
export { default as pic13 } from "../../../public/pics/pic13.jpg"
export { default as pic14} from "../../../public/pics/pic14.jpg"
export { default as pic15 } from "../../../public/pics/pic15.jpg"
export { default as pic17 } from "../../../public/pics/pic17.jpg"
export { default as pic18 } from "../../../public/pics/pic18.jpg"
export { default as pic20} from "../../../public/pics/pic20.jpg"
export { default as pic23 } from "../../../public/pics/pic23.jpg"
export { default as pic26 } from "../../../public/pics/pic26.jpg"
export { default as pic27 } from "../../../public/pics/pic27.jpg"
export { default as pic28 } from "../../../public/pics/pic28.jpg"
export { default as pic29 } from "../../../public/pics/pic29.jpg"
export { default as pic30 } from "../../../public/pics/pic30.jpg"
export { default as pic31 } from "../../../public/pics/pic31.jpg"
export { default as pic32 } from "../../../public/pics/pic32.jpg"
export { default as pic33 } from "../../../public/pics/pic33.jpg"
export { default as pic34 } from "../../../public/pics/pic34.jpg"
export { default as pic35 } from "../../../public/pics/pic35.jpg"
export { default as pic36 } from "../../../public/pics/pic36.jpg"
export { default as pic37 } from "../../../public/pics/pic37.jpg"
export { default as pic38 } from "../../../public/pics/pic38.jpg"
export { default as pic39 } from "../../../public/pics/pic39.jpg"
export { default as pic40 } from "../../../public/pics/pic40.jpg"
export { default as pic41 } from "../../../public/pics/pic41.jpg"
export { default as pic42 } from "../../../public/pics/pic42.jpg"

