import type { Metadata } from 'next'
import {Poppins} from 'next/font/google'
import Navbar from "@/components/Navbar/Navbar"
import './globals.css'
import Container from '@/components/Container/Container'
import Footer from '@/components/Footer/Footer'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '400', '500', '600'],
  variable: '--font-poppins',
})
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ranger Station',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <Container>
          <Navbar/>
          {children}
          <Footer/>
        </Container>
     
      </body>
    </html>
  )
}
